In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.datasets as dsets
import torch.nn.functional as F
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
torch.manual_seed(2)

C:\Users\cpilo\Hello\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


In [2]:
df = pd.read_csv(r"C:\Users\cpilo\Downloads\df_all_teams_070823.csv")

df_team_data = pd.get_dummies(df.team_abbr)
df_opponent_data = pd.get_dummies(df.opponent_abbr)
col_names = []
for i in df_opponent_data.columns:
    col_names.append('opp_'+i)
df_opponent_data.columns = col_names
game_city = pd.get_dummies(df.game_city)
game_time = pd.get_dummies(df.Time)
game_day = pd.get_dummies(df.Day)
vs_line = pd.get_dummies(df['vs. Line'])
qb_1 = pd.get_dummies(df['QB1'])
opp_qb_1 = pd.get_dummies(df['opp_QB1'])
skill_1 = pd.get_dummies(df['Skill1'])
opp_skill_1 = pd.get_dummies(df['opp_skill1'])
skill_2 = pd.get_dummies(df['Skill2'])
opp_skill_2 = pd.get_dummies(df['opp_skill2'])
skill_3 = pd.get_dummies(df['Skill3'])
opp_skill_3 = pd.get_dummies(df['opp_skill3'])
skill_4 = pd.get_dummies(df['Skill4'])
opp_skill_4 = pd.get_dummies(df['opp_skill4'])
skill_5 = pd.get_dummies(df['Skill5'])
opp_skill_5 = pd.get_dummies(df['opp_skill5'])
oline_1 = pd.get_dummies(df['Oline1'])
opp_oline_1 = pd.get_dummies(df['opp_oline1'])
oline_2 = pd.get_dummies(df['Oline2'])
opp_oline_2 = pd.get_dummies(df['opp_oline2'])
oline_3 = pd.get_dummies(df['Oline3'])
opp_oline_3 = pd.get_dummies(df['opp_oline3'])
oline_4 = pd.get_dummies(df['Oline4'])
opp_oline_4 = pd.get_dummies(df['opp_oline4'])
oline_5 = pd.get_dummies(df['Oline5'])
opp_oline_5 = pd.get_dummies(df['opp_oline5'])
dline_1 = pd.get_dummies(df['Dline1'])
opp_dline_1 = pd.get_dummies(df['opp_dline1'])
dline_2 = pd.get_dummies(df['Dline2'])
opp_dline_2 = pd.get_dummies(df['opp_dline2'])
dline_3 = pd.get_dummies(df['Dline3'])
opp_dline_3 = pd.get_dummies(df['opp_dline3'])
lb_1 = pd.get_dummies(df['LB1'])
opp_lb_1 = pd.get_dummies(df['opp_lb1'])
lb_2 = pd.get_dummies(df['LB2'])
opp_lb_2 = pd.get_dummies(df['opp_lb2'])
lb_3 = pd.get_dummies(df['LB3'])
opp_lb_3 = pd.get_dummies(df['opp_lb3'])
lb_4 = pd.get_dummies(df['LB4'])
opp_lb_4 = pd.get_dummies(df['opp_lb4'])
cb_1 = pd.get_dummies(df['CB1'])
opp_cb_1 = pd.get_dummies(df['opp_cb1'])
cb_2 = pd.get_dummies(df['CB2'])
opp_cb_2 = pd.get_dummies(df['opp_cb2'])
ss = pd.get_dummies(df['SS'])
opp_ss = pd.get_dummies(df['opp_ss'])
fs = pd.get_dummies(df['FS'])
opp_fs = pd.get_dummies(df['opp_fs'])

col_names = []
for i in vs_line.columns:
    col_names.append('spread_'+i)
vs_line.columns = col_names
OU_result = pd.get_dummies(df['OU Result'])
col_names = []
for i in OU_result.columns:
    col_names.append('OU_'+i)
OU_result.columns = col_names
model_vars = ['date_day', 'date_month', 'date_year', 'Week', 'Spread', 'OverUnder','days_rest', 'team_season_wins', 
              'team_season_losses', 'prev_week_total', 'prev_week_ptsdiff',
              'prev_week_ydsoff', 'prev_week_ydsdef', 'prev_week_ptsoff', 
              'prev_week_ptsdef', 'prev_week_TOoff', 'prev_week_TOdef', 
              'prev_week_seasptsdiff', 'prev_week_seasptsoff', 
              'prev_week_seasptsdef', 'prev_week_seasydsoff', 'prev_week_seasydsdef', 
              'prev_week_seasTOoff', 'prev_week_seasTOdef', 'prev_week_avgpts', 'prev_week_TOdiff',
              'prev_week_avgTOdiff', 'prev_week_avgptsdiff', 'prev_week_avgptsoff', 
              'prev_week_avgptsdef', 'prev_week_avgydsoff', 'prev_week_avgydsdef', 
              'prev_week_avgTOoff', 'prev_week_avgTOdef', 'Opp_days_rest', 'Opp_team_season_wins',
              'Opp_team_season_losses', 'opp_prev_week_total', 'opp_prev_week_pts_diff', 
              'opp_prev_week_ydsoff', 'opp_prev_week_ydsdef', 'opp_prev_week_ptsoff', 'opp_prev_week_ptsdef', 
              'opp_prev_week_TOoff', 'opp_prev_week_TOdef', 'opp_prev_week_seasptsdiff', 
              'opp_prev_week_seasptsoff', 'opp_prev_week_seasptsdef', 'opp_prev_week_seasydsoff',
              'opp_prev_week_seasydsdef', 'opp_prev_week_seasTOoff', 'opp_prev_week_seasTOdef',
              'opp_prev_week_avgpts', 'opp_prev_week_TOdiff', 'opp_prev_week_avgTOdiff',
              'opp_prev_week_avgptsdiff', 'opp_prev_week_avgptsoff', 'opp_prev_week_avgptsdef',
              'opp_prev_week_avgydsoff', 'opp_prev_week_avgydsdef', 'opp_prev_week_avgTOoff',
              'opp_prev_week_avgTOdef', 'prev_week_avgspreaddif', 'prev_week_avgoverdif', 'prev_week_avgspread',
              'prev_week_avgover', 'prev_week_seasspreadwin', 'prev_week_seasspreadloss', 'prev_week_seasspreadtie',
              'prev_week_seasoverwin', 'prev_week_seasoverloss', 'prev_week_seasovertie', 'prev_week_seastotspread',
              'prev_week_seastotover', 'prev_week_spreadwin', 'prev_week_spreadloss', 'prev_week_spreadtie',
              'prev_week_overwin', 'prev_week_overloss', 'prev_week_overtie', 'prev_week_spreaddiff', 
              'prev_week_overdiff', 'opp_prev_week_avgspreaddif', 'opp_prev_week_avgoverdif',
              'prev_week_streakw', 'prev_week_streakl', 'prev_week_streakspreadw', 'prev_week_streakspreadl',
              'prev_week_streakoverw', 'prev_week_streakoverl', 'prev_week_avgspread', 'prev_week_avgover', 
              'prev_week_seasspreadwin', 'prev_week_seasspreadloss', 'prev_week_seasspreadtie', 'prev_week_seasoverwin',
              'prev_week_seasoverloss', 'prev_week_seasovertie', 'prev_week_seastotspread', 'prev_week_seastotover',
              'prev_week_spreadwin', 'prev_week_spreadloss', 'prev_week_spreadtie', 'prev_week_overwin',
              'prev_week_overloss', 'prev_week_overtie', 'prev_week_spreaddiff', 'prev_week_overdiff',              
              'opp_prev_week_avgspread', 'opp_prev_week_avgover', 'opp_prev_week_seasspreadwin', 
              'opp_prev_week_seasspreadloss', 'opp_prev_week_seasspreadtie', 'opp_prev_week_seasoverwin',
              'opp_prev_week_seasoverloss', 'opp_prev_week_seasovertie', 'opp_prev_week_seastotspread', 
              'opp_prev_week_seastotover', 'opp_prev_week_spreadwin', 'opp_prev_week_spreadloss', 
              'opp_prev_week_spreadtie', 'opp_prev_week_overwin', 'opp_prev_week_overloss', 
              'opp_prev_week_overtie', 'opp_prev_week_spreaddiff', 'opp_prev_week_overdiff',
              'opp_prev_week_avgspread', 'opp_prev_week_avgover', 'opp_prev_week_seasspreadwin',
              'opp_prev_week_seasspreadloss', 'opp_prev_week_seasspreadtie', 'opp_prev_week_seasoverwin',
              'opp_prev_week_seasoverloss', 'opp_prev_week_seasovertie', 'opp_prev_week_seastotspread', 
              'opp_prev_week_seastotover', 'opp_prev_week_spreadwin', 'opp_prev_week_spreadloss',
              'opp_prev_week_spreadtie', 'opp_prev_week_overwin', 'opp_prev_week_overloss',
              'opp_prev_week_overtie', 'opp_prev_week_spreaddiff', 'opp_prev_week_overdiff',
              'opp_prev_week_streakw', 'opp_prev_week_streakl', 'opp_prev_week_streakspreadw',
              'opp_prev_week_streakspreadl', 'opp_prev_week_streakoverw', 'opp_prev_week_streakoverl']
              

df_rfc_data = df[model_vars]
df_final_data = pd.concat([df_rfc_data, df_team_data, df_opponent_data, game_city, qb_1, opp_qb_1,
                           skill_1, opp_skill_1, skill_2, opp_skill_2, skill_3, opp_skill_3,
                           skill_4, opp_skill_4, skill_5, opp_skill_5, oline_1, opp_oline_1,
                           oline_2, opp_oline_2, oline_3, opp_oline_3, oline_4, opp_oline_4,
                           oline_5, opp_oline_5, dline_1, opp_dline_1, dline_2, opp_dline_2,
                           dline_3, opp_dline_3, lb_1, opp_lb_1, lb_2, opp_lb_2, lb_3, opp_lb_3, 
                           lb_4, opp_lb_4, cb_1, opp_cb_1, cb_2, opp_cb_2, ss, opp_ss, fs, opp_fs,
                           game_time, game_day, vs_line, OU_result], axis = 'columns')

df_final_data = df_final_data[df_final_data['Week'] != 1]
df_final_data = df_final_data.dropna(axis = 'index')
df_train = df_final_data[df_final_data['date_year'] < 2021]
df_test = df_final_data[df_final_data['date_year'] >= 2021]
df_train = df_train.replace({True:1, False:0})
df_test = df_test.replace({True:1, False:0})
print(len(df_train.columns))
df_train

611


date_day  date_month  date_year  Week  Spread  OverUnder  days_rest  \
1           20           9       2009     2     3.0       44.0        7.0   
2           27           9       2009     3    -3.0       49.0        7.0   
3           11          10       2009     4    -6.0       51.0       14.0   
4           18          10       2009     5     3.0       46.0        7.0   
5           25          10       2009     6     8.0       47.0        7.0   
...        ...         ...        ...   ...     ...        ...        ...   
6161        26          11       2020    11     2.5       46.0        4.0   
6162         7          12       2020    12     6.5       43.5       11.0   
6163        13          12       2020    13     3.0       43.5        6.0   
6164        20          12       2020    14     6.0       44.5        7.0   
6165        27          12       2020    15     1.0       41.5        7.0   

      team_season_wins  team_season_losses  prev_week_total  ...  Sun  Thu  \
1                  0.0                 1.0             36.0  ...    1    0   
2                  1.0                 1.0             48.0  ...    1    0   
3                  1.0                 2.0             41.0  ...    1    0   
4                  2.0                 2.0             49.0  ...    1    0   
5                  3.0                 2.0             30.0  ...    1    0   
...                ...                 ...              ...  ...  ...  ...   
6161               3.0                 7.0             29.0  ...    0    1   
6162               4.0                 7.0             57.0  ...    0    0   
6163               5.0                 7.0             40.0  ...    1    0   
6164               6.0                 7.0             38.0  ...    1    0   
6165               6.0                 8.0             35.0  ...    1    0   

      Tue  Wed  spread_Lost  spread_Push  spread_Won  OU_Over  OU_Push  \
1       0    0            0            0           1        1        0   
2       0    0            1            0           0        0        0   
3       0    0            0            0           1        0        0   
4       0    0            0            0           1        0        0   
5       0    0            0            0           1        0        0   
...   ...  ...          ...          ...         ...      ...      ...   
6161    0    0            0            0           1        1        0   
6162    0    0            0            0           1        0        0   
6163    0    0            0            0           1        0        0   
6164    0    0            0            0           1        0        0   
6165    0    0            1            0           0        0        0   

      OU_Under  
1            0  
2            1  
3            1  
4            1  
5            1  
...        ...  
6161         0  
6162         1  
6163         1  
6164         1  
6165         1  

[5720 rows x 611 columns]

In [3]:
df_col_names = df_train.drop(['spread_Won', 'spread_Lost', 'spread_Push', 'OU_Over', 'OU_Push', 'OU_Under'], axis = 'columns')

In [4]:
df_col_names

date_day  date_month  date_year  Week  Spread  OverUnder  days_rest  \
1           20           9       2009     2     3.0       44.0        7.0   
2           27           9       2009     3    -3.0       49.0        7.0   
3           11          10       2009     4    -6.0       51.0       14.0   
4           18          10       2009     5     3.0       46.0        7.0   
5           25          10       2009     6     8.0       47.0        7.0   
...        ...         ...        ...   ...     ...        ...        ...   
6161        26          11       2020    11     2.5       46.0        4.0   
6162         7          12       2020    12     6.5       43.5       11.0   
6163        13          12       2020    13     3.0       43.5        6.0   
6164        20          12       2020    14     6.0       44.5        7.0   
6165        27          12       2020    15     1.0       41.5        7.0   

      team_season_wins  team_season_losses  prev_week_total  ...  9:35AM  \
1                  0.0                 1.0             36.0  ...       0   
2                  1.0                 1.0             48.0  ...       0   
3                  1.0                 2.0             41.0  ...       0   
4                  2.0                 2.0             49.0  ...       0   
5                  3.0                 2.0             30.0  ...       0   
...                ...                 ...              ...  ...     ...   
6161               3.0                 7.0             29.0  ...       0   
6162               4.0                 7.0             57.0  ...       0   
6163               5.0                 7.0             40.0  ...       0   
6164               6.0                 7.0             38.0  ...       0   
6165               6.0                 8.0             35.0  ...       0   

      9:36AM  9:37AM  Fri  Mon  Sat  Sun  Thu  Tue  Wed  
1          0       0    0    0    0    1    0    0    0  
2          0       0    0    0    0    1    0    0    0  
3          0       0    0    0    0    1    0    0    0  
4          0       0    0    0    0    1    0    0    0  
5          0       0    0    0    0    1    0    0    0  
...      ...     ...  ...  ...  ...  ...  ...  ...  ...  
6161       0       0    0    0    0    0    1    0    0  
6162       0       0    0    1    0    0    0    0    0  
6163       0       0    0    0    0    1    0    0    0  
6164       0       0    0    0    0    1    0    0    0  
6165       0       0    0    0    0    1    0    0    0  

[5720 rows x 605 columns]

In [5]:
Y = torch.tensor(df_train['OU_Over'].values).float()
X = torch.tensor(df_train.drop(['spread_Won', 'spread_Lost', 'spread_Push', 'OU_Over', 'OU_Push', 'OU_Under'], 
                               axis = 'columns').values).float()
x_train, x_val, y_train, y_val = train_test_split(X, Y, test_size = 0.3)
y_test = torch.tensor(df_test['OU_Over'].values).float()
x_test = torch.tensor(df_test.drop(['spread_Won', 'spread_Lost', 'spread_Push', 'OU_Over', 'OU_Push', 'OU_Under'], 
                                   axis = 'columns').values).float()

In [6]:
x_test

tensor([[3.0000e+00, 1.0000e+00, 2.0210e+03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [3.0000e+00, 1.0000e+00, 2.0210e+03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [3.0000e+00, 1.0000e+00, 2.0210e+03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [2.6000e+01, 1.2000e+01, 2.0210e+03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [2.0000e+00, 1.0000e+00, 2.0220e+03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [9.0000e+00, 1.0000e+00, 2.0220e+03,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]])

In [7]:
training_x = pd.DataFrame(x_train.numpy())
training_x.to_csv(r"C:\Users\cpilo\Documents\NFL_Models\x_train.csv", index = False)
training_y = pd.Series(y_train.numpy())
training_y.to_csv(r"C:\Users\cpilo\Documents\NFL_Models\y_train.csv", index = False)
val_x = pd.DataFrame(x_val.numpy())
val_x.to_csv(r"C:\Users\cpilo\Documents\NFL_Models\x_val.csv", index = False)
val_y = pd.Series(y_val.numpy())
val_y.to_csv(r"C:\Users\cpilo\Documents\NFL_Models\y_val.csv", index = False)

In [8]:
# create model for relu activation
class neural_net(nn.Module):
    def __init__(self, D_in, H1, H2, H3, D_out):#H4, H5, H6, D_out):
        super(neural_net, self).__init__()
        #Define our leaky relu activation function
        self.relu = nn.LeakyReLU(0.01)
        #define our sigmoid function for our output layer
        self.sig = nn.Sigmoid()
        self.linear1 = nn.Linear(D_in, H1)
        #we will apply batch normalization to the output of each hidden layer
        self.batch1 = nn.BatchNorm1d(H1)
        self.linear2 = nn.Linear(H1, H2)
        self.batch2 = nn.BatchNorm1d(H2)
        self.linear3 = nn.Linear(H2, H3)
        self.batch3 = nn.BatchNorm1d(H3)
        self.linear4 = nn.Linear(H3, D_out)
    def forward(self, x):
        #call our network
        #we apply batch normalization before our activation function
        x = self.relu(self.batch1(self.linear1(x)))
        x = self.relu(self.batch2(self.linear2(x)))
        x = self.relu(self.batch3(self.linear3(x)))
        x = self.sig(self.linear4(x))
        return x

In [16]:
from sklearn.metrics import mean_squared_error as mse
# define training function
def train(model, criterion, x_train, x_val, y_train, y_val, optimizer, epochs = 100):
    i = 0
    useful_stuff = {'training_loss': [], 'validation_accuracy': []}
    for epoch in range(epochs):
        total = 0
        optimizer.zero_grad()
        yhat = model(x_train)
        loss = criterion(yhat, y_train.unsqueeze(1))
        loss.backward()
        optimizer.step()
        useful_stuff['training_loss'].append(loss.item())
        #validation
        z = model(x_val)
        MSE = criterion(z, y_val.unsqueeze(1))
        useful_stuff['validation_accuracy'].append(MSE)
        if (epoch%200==0):
            print('epoch {}, loss {}'.format(epoch, loss.item()/1))
        
    return useful_stuff

In [18]:
# Create criterion function
criterion = nn.MSELoss()

In [11]:
# train model with relu
model = neural_net(605, 235, 100, 40, 1)
optimizer = optim.SGD(model.parameters(), lr = 0.000001)
training_results = train(model, criterion, x_train, x_val, y_train, y_val, optimizer, 2500)

epoch 0, loss 0.2566361427307129
epoch 200, loss 0.2565983831882477
epoch 400, loss 0.2565596103668213
epoch 600, loss 0.2565206289291382
epoch 800, loss 0.2564818561077118
epoch 1000, loss 0.25644299387931824
epoch 1200, loss 0.2564041316509247
epoch 1400, loss 0.25636571645736694
epoch 1600, loss 0.2563268840312958
epoch 1800, loss 0.2562876343727112
epoch 2000, loss 0.2562485337257385
epoch 2200, loss 0.2562089264392853
epoch 2400, loss 0.2561686933040619


In [12]:
training_results['training_loss'][len(training_results['training_loss'])-1]

0.2561485767364502

In [13]:
epoch = 8000
loss = training_results['training_loss'][len(training_results['training_loss'])-1]
PATH = r'C:\Users\cpilo\Documents\NFL_Models\nfl_batch_model1'
#save our model
torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': loss,
            }, PATH)

In [14]:
model.state_dict()

OrderedDict([('linear1.weight',
              tensor([[ 0.0093, -0.0097,  0.0111,  ..., -0.0032,  0.0351,  0.0035],
                      [-0.0149, -0.0063, -0.0359,  ...,  0.0256,  0.0210,  0.0283],
                      [-0.0061,  0.0085,  0.0003,  ..., -0.0248, -0.0059, -0.0227],
                      ...,
                      [ 0.0084,  0.0354,  0.0326,  ...,  0.0044, -0.0214,  0.0067],
                      [-0.0034, -0.0237,  0.0043,  ...,  0.0362,  0.0141,  0.0185],
                      [-0.0162,  0.0178, -0.0222,  ..., -0.0211, -0.0069,  0.0194]])),
             ('linear1.bias',
              tensor([-0.0261,  0.0360, -0.0307, -0.0211, -0.0145, -0.0137,  0.0054, -0.0342,
                      -0.0303,  0.0081,  0.0090,  0.0391,  0.0246, -0.0144, -0.0052, -0.0096,
                      -0.0098,  0.0393, -0.0057,  0.0137, -0.0088,  0.0092,  0.0126,  0.0022,
                      -0.0275, -0.0284, -0.0109,  0.0014,  0.0117,  0.0254, -0.0023,  0.0243,
                      -0.015

In [11]:
#here we load our saved model
#We define our hyperparameters
model1 = neural_net(605, 235, 100, 40, 1)
optimizer = optim.SGD(model1.parameters(), lr = 0.000001)
checkpoint = torch.load(PATH)  # load the saved checkpoint

# load the saved information back
model1.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
epoch = checkpoint['epoch']
loss = checkpoint['loss']

In [12]:
model1.train()

neural_net(
  (relu): LeakyReLU(negative_slope=0.01)
  (sig): Sigmoid()
  (linear1): Linear(in_features=605, out_features=235, bias=True)
  (batch1): BatchNorm1d(235, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (linear2): Linear(in_features=235, out_features=100, bias=True)
  (batch2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (linear3): Linear(in_features=100, out_features=40, bias=True)
  (batch3): BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (linear4): Linear(in_features=40, out_features=1, bias=True)
)

In [13]:
model1.state_dict()

OrderedDict([('linear1.weight',
              tensor([[ 0.0093, -0.0097,  0.0111,  ..., -0.0032,  0.0351,  0.0035],
                      [-0.0149, -0.0063, -0.0359,  ...,  0.0256,  0.0210,  0.0283],
                      [-0.0061,  0.0085,  0.0003,  ..., -0.0248, -0.0059, -0.0227],
                      ...,
                      [ 0.0084,  0.0354,  0.0326,  ...,  0.0044, -0.0214,  0.0067],
                      [-0.0034, -0.0237,  0.0043,  ...,  0.0362,  0.0141,  0.0185],
                      [-0.0162,  0.0178, -0.0222,  ..., -0.0211, -0.0069,  0.0194]])),
             ('linear1.bias',
              tensor([-0.0261,  0.0360, -0.0307, -0.0211, -0.0145, -0.0137,  0.0054, -0.0342,
                      -0.0303,  0.0081,  0.0090,  0.0391,  0.0246, -0.0144, -0.0052, -0.0096,
                      -0.0098,  0.0393, -0.0057,  0.0137, -0.0088,  0.0092,  0.0126,  0.0022,
                      -0.0275, -0.0284, -0.0109,  0.0014,  0.0117,  0.0254, -0.0023,  0.0243,
                      -0.015

In [19]:
#we can call train to update our loaded model
training_results = train(model1, criterion, x_train, x_val, y_train, y_val, optimizer, 500)

epoch 0, loss 0.2564111351966858
epoch 200, loss 0.25637346506118774
epoch 400, loss 0.2563360929489136
